import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";

import { auth } from "@/auth";
import { raleway, unbounded } from "@/app/fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "DokaKarton - картонная упаковка из  эко материалов",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="ru">
        <body className={`${raleway.className} ${unbounded.variable}`}>
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
